# Generated by Django 5.0.3 on 2024-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "room_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hostel_block",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
