# Generated by Django 5.0.3 on 2024-03-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulathon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsystem", models.CharField(max_length=255)),
                ("assembly", models.CharField(max_length=255, null=True)),
                ("component", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("qty", models.PositiveIntegerField(blank=True, null=True)),
                ("min_qty", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "add_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="hostel_block",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="room_number",
        ),
    ]
